/**
 * This file is part of i5/OS Programmer's Toolkit.
 * 
 * Copyright (C) 2010, 2011  Junlei Li (李君磊).
 * 
 * i5/OS Programmer's Toolkit is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * i5/OS Programmer's Toolkit is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with i5/OS Programmer's Toolkit.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/**
 * @file uuid.java
 *
 * Issuing the GENUUID instruction to generate a UUID in java via MI Portal.
 *
 * @remark This program can run locally at an IBM i server or remotely at a client PC.
 */

import com.ibm.as400.access.*;

public class uuid {

    /// ctor
    public static void main(String[] args) {

        byte[] inst_inx = {  // ubin(2) instruction index, hex 0001 for MATMATR
            0x00, 0x02
        };
        byte[] uuid_tmpl = { // length the UUID instruction template is 32
            0x00, 0x00, 0x00, 0x20, // bin(4) bytes-in = 32
            0x00, 0x00, 0x00, 0x00, // bin(4) bytes-out
            0x00, 0x00, 0x00, 0x00, // char(8) reserved
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, // char(16) returned UUID
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00
        };

        AS400 i = new AS400();  // in case running at an IBM i server
        ProgramParameter[] plist = new ProgramParameter[] {
            new ProgramParameter(inst_inx),  // input, ubin(2) instruction index
            new ProgramParameter(uuid_tmpl, 32) // inout, instruction template of GENUUID
        };

        ProgramCall portal = new ProgramCall(i,
                                             "/qsys.lib/i5toolkit.lib/miportal.pgm",
                                             plist
                                             );

        try {
            if(!portal.run())
                System.out.println("Oops!");
            else {
                byte[] tmpl = plist[1].getOutputData();
                String uuid = "";
                long l = 0;
                for(int j = 0; j < 8; j++)
                    l += ((long)tmpl[16 + j]) << ((7 - j) * 8);
                uuid += java.lang.Long.toHexString(l);

                l = 0;
                for(int j = 0; j < 8; j++)
                    l += ((long)tmpl[24 + j]) << ((7 - j) * 8);
                uuid += java.lang.Long.toHexString(l);

                System.out.println("UUID generated by MI instruction GENUUID: " + uuid);
                /* The output might like the following:
                  UUID generated by MI instruction GENUUID: 215f280084b9194cab860003ac117d94
                 */
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

}
